import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import ReduxProvider from "@/redux/ReduxProvider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Royal IT BD Shop -2 | Ecommerce website mady by NextJs & Shadcn UI",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
  openGraph: {
    title: "Royal IT BD Shop -2 | Ecommerce website mady by NextJs & Shadcn UI",
    description: "The React Framework for the Web",
    url: "https://nextjs.org",
    siteName: "Next.js",
    images: [
      {
        url: `${process.env.HOST_URL}/og-image-home.PNG`, // Dynamic og route
        width: 800,
        height: 600,
      },
      {
        url: `${process.env.HOST_URL}/og-image-home.PNG`, // Dynamic og route
        width: 1800,
        height: 1600,
        alt: "My custom alt",
      },
    ],
    locale: "en_US",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen font-sans antialiased bg-muted/50",
          fontSans.variable
        )}
      >
        {/* <SidebarProvider> */}
        {/* <AppProvider /> */}
        <ReduxProvider>
          {/* <SidebarTrigger /> */}
          {children}
        </ReduxProvider>
        {/* </SidebarProvider> */}
      </body>
    </html>
  );
}
